# Generated by ruby-bindgen (1.0.0)

require 'ffi'

module Proj
  module Api
    extend FFI::Library

    def self.library_names
      ["proj"]
    end

    def self.library_versions
      ["9_1", "9", "25", "22", "19", "17", "15", "14", "13", "12", "11"]
    end

    def self.search_names
      result = Array.new
      self.library_names.each do |name|
        result << "lib#{name}"
        self.library_versions.each do |version|
          case RbConfig::CONFIG['host_os']
            when /darwin|mac os/
              result << "lib#{name}.#{version}"
            when /mingw/
              result << "lib#{name}-#{version}"
            when /mswin/
              result << "#{name}_#{version}"
            else
              result << "lib#{name}.so.#{version}"
          end
        end
      end
      result
    end

    if ENV['PROJ_LIB_PATH']
      ffi_lib self.search_names.map { |name| File.join(ENV['PROJ_LIB_PATH'], name) } + self.search_names
    else
      ffi_lib self.search_names
    end
  end
end

require_relative 'proj_version'
require_relative './proj'
require_relative './proj_experimental'
