name: proj4rb

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]
        ruby: [3.2, 3.3]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CPU architecture
        run: uname -p
      - name: Install Proj (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libproj22
      - name: Install Proj (Mac)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install proj
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
