name: proj4rb

on: [push, pull_request]

jobs:
  proj_8:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ruby: [3.2, 3.3]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Proj
        run: sudo apt-get install libproj22
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test