name: proj4rb

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.2', '3.3', '3.4', '4.0']
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: CPU architecture
        if: "!startsWith(matrix.os, 'windows')"
        run: uname -p
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Proj (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libproj-dev
      - name: Install Proj (Mac)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install proj
      - name: Install Proj (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: cmd
        run: ridk exec sh -c "pacman --sync --refresh --needed --noconfirm ${MINGW_PACKAGE_PREFIX}-proj"
      - name: Test
        run: bundle exec rake test
